### ISSUE TITLE
Support for forge

### ISSUE THREAD

**Issue by edkolev** [emacs-evil/evil-magit#54] opened 2018-12-23 21:12 UTC
Now that forge's been released, it might be a good idea to consider what binding would be appropriate. I'm not sure if evil-magit is the best place for such a binding to be defined though, evil-collection also seems like an option.

Looking at [here](https://emacsair.me/2018/12/19/forge-0.1/), `'` is the default binding, which is now used for Submodules by evil-magit.

**Comment by Linuus** [comment] 2018-12-26 19:57
Yes! This would be awesome!

**Comment by yuhan0** [comment] 2018-12-27 16:41
As a quick reference, I went over all the current bindings in magit-status-mode, and found the following keys still up for grabs:  

-   `5-9` are digit-argument, not very useful with 1-4 being bound to `magit-show-level-*` commands
-   `H` (also bound by `magithub` and the horizontal-movement setting)
-   `J`
-   `Q`
-   `i/I` both bound to ignore-popup, maybe one could be rebound?
-   `p/P` both push
-   `v/V` both activate evil-visual-line
-   `;`, `` ` ``, `~`, `*`, `#`, `%`, etc. symbols

None of these options seem particularly mnemonic, but for what it's worth I went with `` ` `` in my own config, mostly because of visual similarity to magit's `'` default binding.

**Comment by justbur** [comment] 2018-12-28 02:01
I haven't tried forge yet. I'm open to suggestions for the key binding. `Q` and `J` are interesting. I was also thinking about `@`, but I don't have a strong opinion.

**Comment by edkolev** [comment] 2018-12-28 09:09
How about using the default `'` and binding submodules to something else, would that be an option?

**Comment by justbur** [comment] 2018-12-28 10:57
Definitely an option but that seems more disruptive

**Comment by Linuus** [comment] 2018-12-28 16:09
I think it’s nice to keep as many default bindings as possible. I do understand if you are hesitant to changing the binding for submodules though.

**Comment by yuhan0** [comment] 2018-12-29 13:57
The issue is submodule and subtree popup bindings are a lower/uppercase pair ( `'` / `"` , originally `o` / `O`). Binding submodules alone to something else wouldn't be optimal, and the only other easily accesible pair available is `` ` `` / `~` .  

`@` might be a good option too - it's what Spacemacs binds the magithub popup to, and vaguely meaningful (your git repos being hosted "at" a forge)  

But it is rather more inconvenient to type, and I imagine most users would be using forge commands more frequently than subtree/submodule ones?

**Comment by justbur** [comment] 2018-12-29 16:19
How about `gh`?

**Comment by Linuus** [comment] 2018-12-30 10:10
I’d prefer one key to be consistent with the other commands.

**Comment by yuhan0** [comment] 2019-01-01 12:04
Same here. As a side note, it would also clash with the spacemacs convention of "gh" navigating to a parent heading.

**Comment by Linuus** [comment] 2019-01-01 15:50
Hm, perhaps `@` is not a good idea since it would override the evil macro execution command.

**Comment by justbur** [comment] 2019-01-11 14:43
I like the following although this is more drastic

  - Make `p` pull
  - Make `F` forge

I'm not sure if putting push so close to pull is a good idea, but it's easier to remember. Of course, it's going to throw people off for a bit

**Comment by Linuus** [comment] 2019-01-11 15:11
I like it 👍

**Comment by justbur** [comment] 2019-01-16 17:22
See 49978d0. Note that the changes only take affect after forge is loaded. The default bindings will be in place before that.

**Comment by Linuus** [comment] 2019-01-16 17:46
Great! Thanks @justbur

**Comment by Linuus** [comment] 2019-01-17 07:46
@justbur Small nitpick... Would it be possible to move the `P` in the `magit-dispatch-popup` to be after `p`? This is how it looks now:
![screen shot 2019-01-17 at 08 44 26](https://user-images.githubusercontent.com/379823/51302960-36b58c80-1a34-11e9-81f5-e61ac011d359.png)

All the lowercase and uppercase letters are next to each other but `p` and `P`.

**Comment by justbur** [comment] 2019-01-17 12:01
Yes, try 49978d0

**Comment by Linuus** [comment] 2019-01-17 15:23
@justbur I think that is what I am running? Otherwise I wouldn't have forge on `F` etc?

**Comment by justbur** [comment] 2019-01-17 15:58
@Linuus Sorry, I thought I had pushed the change. It's c3eae3b2347c4b1798d6d05de18ad073dbbb27d3 which is available now

**Comment by justbur** [comment] 2019-02-03 01:18
Any thoughts from people in this thread on the new bindings? It was inevitable, but the people who don't like them showed up in #60. I can address some of those problems, but I'm wondering if anyone wants me to revert them entirely here.

**Comment by justbur** [comment] 2019-02-03 04:45
ok, I'll revert it for now.

**Comment by Linuus** [comment] 2019-02-03 08:34
For the bindings have worked out well. No wrong pushing :) I’m, of course, fine with moving to a better key binding. 

Perhaps `#` is fine?

**Comment by justbur** [comment] 2019-02-05 01:54
Thanks @Linuus. I think they're sensible, but do take some getting used to. I think there are legitimate uses for `#`. I thought of `~` today, which I think is interesting for forge. There's also `@`, which seems reasonable too.

**Comment by Miciah** [comment] 2019-02-05 02:21
What do you think of <kbd>C</kbd> (upper-case letter c)? It does not conflict with any key binding from Magit, its Evil binding (`evil-change-line`) is not useful in the Magit buffer, its position tends to be a little more stable than punctuation marks' across different keyboard layouts, and after all, Forge is for **C**ollaboration.

**Comment by Linuus** [comment] 2019-02-05 07:51
As I mentioned above I don’t think @ is good since it would break evil macros. Even though I don’t know if I’ve ever used them in Magit I can imagine they are useful.

**Comment by syl20bnr** [comment] 2019-02-09 20:30
Maybe we could use the binding that was used for `magit-gh-pulls` which becomes obsolete now we have `forge`. The binding was `#`.

The issue with `~` is that it can be a dead key with international layouts (which I use 👼 ).

**Comment by syl20bnr** [comment] 2019-02-09 20:31
`@` is already used by `magithub` if I'm not mistaken. Maybe `magithub` will become obsolete because of `forge` as well.

**Closed** 2019-02-16 17:07 UTC

**Comment by justbur** [comment] 2019-02-16 17:10
I'm going with `@`. 

@Linuus I'm not sure macros are more useful than the other options, but you can certainly move the binding if it doesn't work for you. 

@syl20bnr I think `#` is useful, and according to magithub's site most of the functionality is available in forge. 

@Miciah `C` is taken in some of the section maps

**Comment by syl20bnr** [comment] 2019-02-16 17:12
Fine with me.

**Comment by Linuus** [comment] 2019-02-16 17:25
@justbur No worries :) I’ll try it out. And I probably have never actually used `@` in Magit yet so it’s probably fine for me as well :)

Good job 👏🏼
